In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import array

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([1,2,3,4,5,"sudh"])

array(['1', '2', '3', '4', '5', 'sudh'], dtype='<U11')

In [6]:
type(np.array([1,2,3,4,5,"sudh"]))

numpy.ndarray

In [7]:
# 1-D Array

np.array([1,2,3,4.0,5.3,6,7])

array([1. , 2. , 3. , 4. , 5.3, 6. , 7. ])

In [8]:
# 2-D Array

np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [9]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [10]:
# dimension of array should be equal
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\MOHIT~1.KUM\AppData\Local\Temp/ipykernel_11632/195332950.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [11]:
# 3-D Array

np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [12]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])

In [13]:
np.array([1,2,3], ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [14]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
# data as tuple instead of list
np.array([(1,2),(4,5)])

array([[1, 2],
       [4, 5]])

In [4]:
arr = np.array([(1,2),(4,5)],dtype = [("a","<i2"),("b","<i8")])

In [5]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [6]:
arr[0][0]

1

In [18]:
type(arr[0][0])

numpy.int16

In [7]:
arr[0][1]

2

In [19]:
type(arr[0][1])

numpy.int64

In [20]:
arr = np.array([(1,2),(4,5)])

In [21]:
arr

array([[1, 2],
       [4, 5]])

In [22]:
arr[0][0]

1

In [23]:
arr[0][1]

2

In [24]:
arr[1][0]

4

In [25]:
arr[1][1]

5

In [26]:
arr[0]

array([1, 2])

In [27]:
type(arr[1][1])

numpy.int32

In [28]:
np.matrix(arr)

matrix([[1, 2],
        [4, 5]])

In [10]:
l = [3,4,5,76,7]

In [11]:
np.array(l)

array([ 3,  4,  5, 76,  7])

In [12]:
np.asanyarray(l)

array([ 3,  4,  5, 76,  7])

In [13]:
np.asarray(l)

array([ 3,  4,  5, 76,  7])

In [15]:
mat = np.matrix(arr)
mat

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [16]:
np.asanyarray(mat)

# here output is a matrix instaed of array as matrix is also a type of array

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [17]:
np.asarray(mat)

# here output is array as asarray converts into only array.

array([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
np.array(mat)

array([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
# is matrix a subclass of array

issubclass(np.matrix, np.ndarray)

True

In [37]:
# is array a subclass of matrix
issubclass(np.ndarray, np.matrix)

False

In [38]:
# asigning value of arr to a
# shallow copy means changes happening anytime will reflect here

a = arr

In [39]:
# deep copy means changes happening to main after the point of copy won't reflect here

b = np.copy(arr)

In [40]:
arr

array([[1, 2],
       [4, 5]])

In [41]:
a[0][0]  = 57

In [42]:
arr

array([[57,  2],
       [ 4,  5]])

In [43]:
b = np.copy(arr)

In [44]:
a[0][1]  = 77

In [45]:
a

array([[57, 77],
       [ 4,  5]])

In [46]:
b

array([[57,  2],
       [ 4,  5]])

#### NOTE: array is mutable

In [47]:
np.fromfunction(lambda i,j : i == j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

#### generating NdArray

In [48]:
np.fromfunction(lambda i,j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [49]:
np.fromfunction(lambda i,j : i**j, (4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [50]:
# list comprehension
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [51]:
# generator
gen = (i*i for i in range(5))

In [52]:
gen

<generator object <genexpr> at 0x000001F14FBC90B0>

In [53]:
# normal generation
for i in gen:
    print(i)

0
1
4
9
16


In [54]:
# generator
gen = (i*i for i in range(5))

In [55]:
# generating data from generator func
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16])

In [56]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [57]:
# from string creating nd array
np.fromstring('1,2,3,4,5,6,7', sep = ',' )

array([1., 2., 3., 4., 5., 6., 7.])

In [58]:
# from string creating nd array
np.fromstring('1,2,3,4,5,6,7', sep = ',', dtype = int )

# here i am defining dtype as int

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
np.fromstring("456 457 3454 34543", sep = ' ', dtype = complex)

array([  456.+0.j,   457.+0.j,  3454.+0.j, 34543.+0.j])

In [60]:
np.fromstring("456 457 3454 34543", sep = ' ', dtype = int)

array([  456,   457,  3454, 34543])

***

In [61]:
l = [3,4,5,67,8]

In [62]:
arr = np.array(l)

In [63]:
type(arr)

numpy.ndarray

In [64]:
arr.ndim

1

In [65]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [66]:
type(arr1)

numpy.ndarray

In [67]:
# dimension of array
arr1.ndim

2

In [68]:
# size of array
arr1.size

12

In [69]:
# shape of data(n*m)
# n is row, m is  column 
arr1.shape

(3, 4)

In [70]:
arr1.dtype

dtype('int32')

In [71]:
# 5 elements in the array
arr.size

5

In [72]:
# dimension of 1-D array
arr.ndim

1

In [73]:
# 1-D Array
arr.shape

(5,)

In [74]:
# 3-D array
arr2 = np.array([[[1,2,3,4],[4,5,6,7],[2,3,47,7]],[[1,2,3,4],[4,5,6,7],[56,78,90,23]]])

In [75]:
arr2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 2,  3, 47,  7]],

       [[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [56, 78, 90, 23]]])

In [76]:
# total elements in array
arr2.size

24

In [77]:
# shape of 3-D Array
arr2.shape

(2, 3, 4)

In [78]:
arr2.ndim

3

In [79]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [80]:
# range function only takes integer as range

list(range(6.6))

# throws error

TypeError: 'float' object cannot be interpreted as an integer

In [81]:
# np.arange accepts floating point number as range input

np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [82]:
# np.arange accepts floating jumpoints

np.arange(6.6, 9, 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [83]:
# going in reverse
# accepting upper bound because of floating point number

np.arange(9, 6, -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6, 6.3])

In [84]:
# upper bound excluding 

np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
# linspace generates 50 data in between 2 end points
# includes upper-bound as float numbers are beeen generated

np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [86]:
np.linspace(1,9)

array([1.        , 1.16326531, 1.32653061, 1.48979592, 1.65306122,
       1.81632653, 1.97959184, 2.14285714, 2.30612245, 2.46938776,
       2.63265306, 2.79591837, 2.95918367, 3.12244898, 3.28571429,
       3.44897959, 3.6122449 , 3.7755102 , 3.93877551, 4.10204082,
       4.26530612, 4.42857143, 4.59183673, 4.75510204, 4.91836735,
       5.08163265, 5.24489796, 5.40816327, 5.57142857, 5.73469388,
       5.89795918, 6.06122449, 6.2244898 , 6.3877551 , 6.55102041,
       6.71428571, 6.87755102, 7.04081633, 7.20408163, 7.36734694,
       7.53061224, 7.69387755, 7.85714286, 8.02040816, 8.18367347,
       8.34693878, 8.51020408, 8.67346939, 8.83673469, 9.        ])

In [87]:
# dividing into 5 equal points

np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [88]:
np.linspace(0.1, 0.11, 10)

array([0.1       , 0.10111111, 0.10222222, 0.10333333, 0.10444444,
       0.10555556, 0.10666667, 0.10777778, 0.10888889, 0.11      ])

In [89]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [90]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [93]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [94]:
np.ones((2,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [95]:
np.ones((2,5,4))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [96]:
np.empty(5)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304, 7.74860419e-304,
       7.74860419e-304])

In [97]:
# generating random data
np.empty((3,4))

array([[4.67296746e-307, 1.69121096e-306, 1.06811083e-306,
        1.20157112e-306],
       [1.60218491e-306, 1.42418987e-306, 1.37961641e-306,
        1.60220528e-306],
       [1.24611266e-306, 9.34598925e-307, 1.24612081e-306,
        1.20930803e+165]])

In [98]:
# represents identity matrix with determinant = 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.full((4,2), 99, dtype = float)

array([[99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.]])

In [52]:
# makes this equal to dimension of arr2 with 4 as value 
np.full_like(arr2, 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [54]:
# Repeat an array

arra = np.array([[1,2,3]])
r1 = np.repeat(arra,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [71]:
# copying one array inside another 

output = np.ones((3,4))
print(output,'\n')

z= np.zeros((3,3))
print('\n',z,'\n')

output[:,1:] = z
print('\n',output)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 


 [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [100]:
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [101]:
# not to include upperbound

np.linspace(2,10,4,endpoint =False)

array([2., 4., 6., 8.])

In [102]:
np.linspace([1,6],4,endpoint=False, axis = 1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [103]:
# transposing the data and changing the axis

np.linspace([1,6],4,endpoint=False, axis = 0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [32]:
# transposing the data and changing the axis

np.linspace([1,6],4,endpoint=False, axis = 0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [104]:
# logarithmic of the data

np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [105]:
np.logspace([2],[3])

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [106]:
np.logspace([2],[3], axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [107]:
np.logspace([2,5],[3], axis = 0)

array([[   100.        , 100000.        ],
       [   104.81131342,  91029.81779915],
       [   109.8541142 ,  82864.27728547],
       [   115.13953993,  75431.20063355],
       [   120.67926406,  68664.88450043],
       [   126.48552169,  62505.51925274],
       [   132.57113656,  56898.66029018],
       [   138.94954944,  51794.74679231],
       [   145.63484775,  47148.66363457],
       [   152.64179672,  42919.34260129],
       [   159.98587196,  39069.39937055],
       [   167.68329368,  35564.80306223],
       [   175.75106249,  32374.57542818],
       [   184.20699693,  29470.51702552],
       [   193.06977289,  26826.9579528 ],
       [   202.35896477,  24420.53094549],
       [   212.09508879,  22229.96482526],
       [   222.29964825,  20235.89647725],
       [   232.99518105,  18420.69969327],
       [   244.20530945,  16768.32936811],
       [   255.95479227,  15264.17967175],
       [   268.26957953,  13894.95494373],
       [   281.1768698 ,  12648.55216855],
       [   

***

In [26]:
d = np.linspace(4,7,40)
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [27]:
# 1-D Data
d.ndim

1

In [28]:
d.shape

(40,)

In [29]:
# reshaping 1-D data into 2-D data
# changing it into (40x1) (40 = rows , 1 = columns)

d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [30]:
# reshaping 1-D data into 3-D data
# (1x20 Matrix of 2 such matrix in 3-D space)

d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

#### NOTE: Even after reshaping the data size should be same

#### rand

In [113]:
# returns data from uniform distribution over (0,1]

np.random.rand(5)

array([0.00184744, 0.88560903, 0.40024272, 0.2778275 , 0.77019019])

#### randn

In [114]:
# returns data from standard normal distribution

np.random.randn(5)

array([-0.77234124, -0.15613138, -0.66063501, -0.62825745,  2.14923392])

In [115]:
# data with 5 rows and 4 columns
np.random.randn(5,4)

array([[ 0.91017456, -0.67995416, -1.13045526,  0.08703252],
       [ 0.14858473,  0.35463951, -1.09847299, -0.68543776],
       [-1.03810719,  1.71694329,  0.1366354 ,  1.18179751],
       [-1.33293247,  0.183156  ,  0.46971322,  0.61908776],
       [-0.26351629, -0.91472053,  0.43226255,  0.68993706]])

In [33]:
np.random.randn(2,3)

array([[ 0.02007043, -1.15190783,  0.64428352],
       [-0.20706539, -1.79758208, -1.52223511]])

In [116]:
np.random.randn(2,2,3)

array([[[ 1.84557023,  0.51810435, -0.03706017],
        [ 0.56646926, -0.39766698,  2.99636719]],

       [[ 0.03039471, -0.47192699,  1.84425574],
        [-1.25924709,  0.80035841, -0.77164547]]])

#### randint

In [117]:
# integer between 5 and 10
np.random.randint(5,10)

5

In [118]:
# generating 4x4 matrix between 5 and 60

np.random.randint(5,60, (4,4))

array([[19, 27, 56, 59],
       [28, 14, 25, 37],
       [58, 39, 48, 31],
       [41, 50, 44, 51]])

In [119]:
arr = np.random.randint(3,9,(3,3))
arr

array([[8, 8, 3],
       [8, 4, 3],
       [4, 7, 4]])

In [110]:
# size is 9 so, reshaping should also have 9 elements
arr.size

25

In [121]:
# reshaping it in 1x9 i.e. 1 row and 9 column

arr.reshape(1,9)

array([[8, 8, 3, 8, 4, 3, 4, 7, 4]])

In [122]:
# reshaping it in 9x1 i.e. 9 row and 1 column

arr.reshape(9,1)

array([[8],
       [8],
       [3],
       [8],
       [4],
       [3],
       [4],
       [7],
       [4]])

In [123]:
# reshaping data in 3-D

arr.reshape(1,1,9)

array([[[8, 8, 3, 8, 4, 3, 4, 7, 4]]])

In [124]:
arr.reshape(3,3,1)

array([[[8],
        [8],
        [3]],

       [[8],
        [4],
        [3]],

       [[4],
        [7],
        [4]]])

In [125]:
arr.reshape(3,-1)

array([[8, 8, 3],
       [8, 4, 3],
       [4, 7, 4]])

In [126]:
arr.reshape(1,-14455)

array([[8, 8, 3, 8, 4, 3, 4, 7, 4]])

In [127]:
# max elelment of array
arr.max()

8

In [128]:
# min element of array
arr.min()

3

#### extracting part of matrix

In [35]:
arr = np.random.randint(4,100, (5,5))
arr

# dimension is 5x5

array([[29,  4, 98, 29, 29],
       [81, 65, 52, 83, 87],
       [63, 11, 41, 12, 98],
       [58, 56, 64, 91, 76],
       [88, 53, 64, 26, 10]])

In [36]:
# going from 3rd row till last
# first 3: is for row
# second 3: is for column

arr[3: , 3: ]

array([[91, 76],
       [26, 10]])

In [37]:
# entire row and column 2nd and 4th
arr[:,[1,3]]

array([[ 4, 29],
       [65, 83],
       [11, 12],
       [56, 91],
       [53, 26]])

In [38]:
arr

array([[29,  4, 98, 29, 29],
       [81, 65, 52, 83, 87],
       [63, 11, 41, 12, 98],
       [58, 56, 64, 91, 76],
       [88, 53, 64, 26, 10]])

In [39]:
arr>10

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [134]:
arr[arr>10]

array([64, 47, 25, 56, 77, 34, 15, 36, 55, 20, 15, 13, 47, 72, 16, 56, 25,
       20, 13, 44, 72])

In [48]:

arr.loc(arr>10)

#will throw error

AttributeError: 'numpy.ndarray' object has no attribute 'loc'

#### Note: .loc doesnot work in numpy

In [135]:
arr*arr

array([[4096, 2209,  625, 3136,   81],
       [5929, 1156,  225, 1296, 3025],
       [ 400,   64,  225,   16,  169],
       [2209,   16, 5184,  256, 3136],
       [ 625,  400,  169, 1936, 5184]])

In [73]:
arr1 = np.random.randint(2,4,(3,3))
arr1

array([[2, 2, 3],
       [2, 3, 3],
       [2, 3, 2]])

In [74]:
arr2 = np.random.randint(2,4,(3,3))
arr2

array([[3, 2, 2],
       [2, 2, 3],
       [3, 2, 3]])

In [75]:
# this is not a matrix multiplication it is just element multiplication

arr1*arr2

array([[6, 4, 6],
       [4, 6, 9],
       [6, 6, 6]])

In [76]:
# 2x2 matrix

arr3 = np.random.randint(2,4,(3,2)) 
arr3

array([[2, 3],
       [3, 3],
       [3, 3]])

In [77]:
arr2 * arr3

# will throw error

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

#### NOTE: Dimension of both the matrix for element multiplication should be same

In [78]:
# This is matrix multiplication

arr1@arr2

array([[19, 14, 19],
       [21, 16, 22],
       [18, 14, 19]])

In [79]:
arr3.shape

(3, 2)

In [80]:
arr2.shape

(3, 3)

### matrix multiplication

In [81]:
# here between arr2 and arr3 matrix multiplication is happening. arr2 = r2*c2, arr3 = r3*c3, so value of c2 = r3,
# then matrix multiplication can happen but still index multiplication won't happen.
# dimension of final matrix will be r2xc3

arr2@arr3

array([[18, 21],
       [19, 21],
       [21, 24]])

In [82]:
# another way of doing matrix multilpication

np.matmul(arr2,arr3)

array([[18, 21],
       [19, 21],
       [21, 24]])

In [143]:
# square of array
arr**2

array([[4096, 2209,  625, 3136,   81],
       [5929, 1156,  225, 1296, 3025],
       [ 400,   64,  225,   16,  169],
       [2209,   16, 5184,  256, 3136],
       [ 625,  400,  169, 1936, 5184]], dtype=int32)

### Broadcasting

What we are doing with 1 row is being done with the entire array

In [144]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [145]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#### column-wise broadcasting

In [146]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [147]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [148]:
arr2  = np.array([1,2,3])
arr2

array([1, 2, 3])

In [149]:
# different dimension array

arr3 * arr2

# will throw error

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

#### Note: for broadcasting the number of columns in both matrix should be same 

#### Row-wise Broadcasting

In [150]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
b = np.array([5,6,7])
b

array([5, 6, 7])

In [152]:
# Way 1
# reshaping b into 3x1

b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [153]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [154]:
# Way 2 
# Making b into 2-D

b = np.array([[5,6,7]])
b

array([[5, 6, 7]])

In [155]:
# Transposing b

b.T

array([[5],
       [6],
       [7]])

In [156]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [157]:
arr = np.random.rand(5,4)
arr

array([[0.91070038, 0.47566259, 0.54350812, 0.79120829],
       [0.19976179, 0.77675375, 0.07508657, 0.62854066],
       [0.92184126, 0.89019137, 0.74698397, 0.43675933],
       [0.25783904, 0.28666166, 0.25759224, 0.38099527],
       [0.08262398, 0.2814103 , 0.59992434, 0.15614724]])

In [158]:
# square root of all the elements

np.sqrt(arr)

array([[0.95430623, 0.68968296, 0.73723003, 0.8894989 ],
       [0.44694719, 0.88133634, 0.27401928, 0.79280556],
       [0.96012565, 0.94349953, 0.86428234, 0.6608777 ],
       [0.50777853, 0.53540794, 0.50753546, 0.61724814],
       [0.28744386, 0.53048119, 0.77454783, 0.3951547 ]])

In [159]:
# exponent value of elements

np.exp(arr)

array([[2.48606311, 1.60908   , 1.7220374 , 2.20606037],
       [1.22111185, 2.17440214, 1.07797746, 1.8748725 ],
       [2.5139149 , 2.43559571, 2.11062469, 1.54768355],
       [1.2941305 , 1.33197348, 1.29381115, 1.46374069],
       [1.08613332, 1.32499714, 1.82198094, 1.16899831]])

In [160]:
np.log10(arr)

array([[-0.04062448, -0.322701  , -0.26479396, -0.10170917],
       [-0.69948757, -0.10971664, -1.12443776, -0.20166663],
       [-0.03534386, -0.05051662, -0.12668872, -0.35975781],
       [-0.58865133, -0.54263039, -0.58906722, -0.41908041],
       [-1.08289391, -0.55066001, -0.22190352, -0.80646569]])

In [161]:
arr1 = np.random.randint(2,5, (5,5))
arr1

array([[3, 2, 4, 2, 2],
       [2, 4, 3, 3, 4],
       [2, 3, 2, 3, 3],
       [2, 3, 4, 4, 3],
       [4, 4, 3, 3, 2]])

In [162]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.60205999, 0.30103   , 0.30103   ],
       [0.30103   , 0.60205999, 0.47712125, 0.47712125, 0.60205999],
       [0.30103   , 0.47712125, 0.30103   , 0.47712125, 0.47712125],
       [0.30103   , 0.47712125, 0.60205999, 0.60205999, 0.47712125],
       [0.60205999, 0.60205999, 0.47712125, 0.47712125, 0.30103   ]])

In [163]:
np.log(arr1)

array([[1.09861229, 0.69314718, 1.38629436, 0.69314718, 0.69314718],
       [0.69314718, 1.38629436, 1.09861229, 1.09861229, 1.38629436],
       [0.69314718, 1.09861229, 0.69314718, 1.09861229, 1.09861229],
       [0.69314718, 1.09861229, 1.38629436, 1.38629436, 1.09861229],
       [1.38629436, 1.38629436, 1.09861229, 1.09861229, 0.69314718]])

#### seed

In [164]:
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

### Stats in Numpy

In [102]:
random_arr = np.random.randint(4,100,(2,6,6))
random_arr

array([[[49, 86, 98, 42, 73, 26],
        [78, 96, 79, 27, 67, 85],
        [45, 43, 15, 58, 51,  7],
        [32, 22, 65, 50, 35, 38],
        [93, 72, 67,  8, 44, 55],
        [ 7, 68, 32, 75, 56, 62]],

       [[85, 35, 99, 56, 50, 16],
        [58, 34, 15, 81, 63, 99],
        [48, 83, 23, 62, 25, 93],
        [13, 23, 39, 23, 63, 87],
        [ 5, 65, 81, 36, 93, 22],
        [34, 36,  6,  9, 77, 63]]])

In [103]:
np.min(random_arr)

5

In [104]:
np.max(random_arr)

99

In [105]:
np.max(random_arr, axis=1)

array([[93, 96, 98, 75, 73, 85],
       [85, 83, 99, 81, 93, 99]])

In [106]:
# sum of matrix
np.sum(random_arr)

3706

In [108]:
# sum of rows
np.sum(random_arr, axis = 1)

array([[304, 387, 356, 260, 326, 273],
       [243, 276, 263, 267, 371, 380]])

In [109]:
# sum of column
np.sum(random_arr, axis = 0)

array([[134, 121, 197,  98, 123,  42],
       [136, 130,  94, 108, 130, 184],
       [ 93, 126,  38, 120,  76, 100],
       [ 45,  45, 104,  73,  98, 125],
       [ 98, 137, 148,  44, 137,  77],
       [ 41, 104,  38,  84, 133, 125]])

In [112]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.array([9,10,11,12])

np.vstack([v1,v2,v3])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
# horizontal stack

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.array([9,10,11,12])
np.hstack([v1,v2,v3])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
v4 = np.zeros((5,4))
print(v4,'\n')

v5 = np.ones((4,5))
print(v5,'\n')

np.hstack([v4,v5])

# throws error

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 



ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 4

In [128]:
v4 = np.zeros((5,4))
print(v4,'\n')

v5 = np.ones((5,3))
print(v5,'\n')

np.hstack([v4,v5])


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



array([[0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.]])